#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: Implement Scope Hierarchy in Symbol Table

set -e

echo "========================================"
echo "C-AL Language Extension - Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_ROOT="/home/klaus/Source/C-AL-Language"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

cd "$PROJECT_ROOT"
if [ -f "package.json" ]; then
    npm install
    echo -e "${GREEN}Root dependencies installed${NC}"
fi

cd "$PROJECT_ROOT/server"
if [ -f "package.json" ]; then
    npm install
    echo -e "${GREEN}Server dependencies installed${NC}"
fi

# ============================================
# COMPILE TYPESCRIPT
# ============================================

echo ""
echo "Compiling TypeScript..."

cd "$PROJECT_ROOT"
npm run compile
echo -e "${GREEN}TypeScript compilation complete${NC}"

# ============================================
# RUN TESTS
# ============================================

echo ""
echo "Running tests to verify setup..."

cd "$PROJECT_ROOT/server"
npm test
echo -e "${GREEN}Tests passed${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: C-AL Language Extension"
echo "Language Server: $PROJECT_ROOT/server"
echo ""
echo "Key files for this task:"
echo "  - server/src/symbols/symbolTable.ts (main changes)"
echo "  - server/src/definition/definitionProvider.ts"
echo "  - server/src/hover/hoverProvider.ts"
echo "  - server/src/completion/completionProvider.ts"
echo "  - server/src/signatureHelp/signatureHelpProvider.ts"
echo ""
echo "Commands:"
echo "  npm run compile     - Compile TypeScript"
echo "  cd server && npm test - Run tests"
echo ""
